trigger: none

pr: none

extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: deviceprovisioningservices
    Artifacts:
      - name: azure-resourcemanager-deviceprovisioningservices
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerdeviceprovisioningservices
    # Only run tests on Windows to avoid duplicating quota-sensitive resource deployment.
    MatrixFilters:
      - pool=.*(win).*
