services:
  echo-sample:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${REGISTRY:-}myagent:latest
    ports:
      - "8088:8088"

    env_file:
      - ../../.env

    environment:
      - APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}

