= Spring Cloud Azure Storage Starter Sample shared library for Java

== Key concepts
== Getting started

This code sample demonstrates how to read and write files with the Spring Resource abstraction for Azure Storage using the
link:../../azure-spring-cloud-starter-storage[Spring Cloud Azure Storage Starter].Running this sample will be charged by Azure.
You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

Running this sample will be charged by Azure.
You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

Maven coordinates:

[source,xml]
----
<dependency>
    <groupId>com.microsoft.azure</groupId>
    <artifactId>spring-starter-azure-storage</artifactId>
</dependency>
----

Gradle coordinates:

[source]
----
dependencies {
    compile group: 'com.microsoft.azure', name: 'spring-starter-azure-storage'
}
----

=== Access key based usage

1. Create https://docs.microsoft.com/en-us/azure/storage/[Azure Storage]

2. Update link:src/main/resources/application.properties[application.properties]

+
....
spring.cloud.azure.storage.account=[storage-account-name]

# Fill storage account access key copied from portal
spring.cloud.azure.storage.access-key=[storage-account-accesskey]

....

=== Credential file based usage

1. Create azure credential file.
Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how to create credential file].
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put credential file under `src/main/resources/`.

3. Create https://docs.microsoft.com/en-us/azure/storage/[Azure Storage].
Or enable auto create resources feature in link:src/main/resources/application.properties[application.properties]:
+
....
spring.cloud.azure.auto-create-resources=true

# Example region is westUS, northchina
spring.cloud.azure.region=[region]
....

5. Update link:src/main/resources/application.properties[application.properties]
+
....

# Enter 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credential-file-path=[credential-file-path]

spring.cloud.azure.resource-group=[resource-group]

spring.cloud.azure.storage.account=[account-name]
....

=== How to run

5. Update link:src/main/resources/application.properties[application.properties]

+
....

# Default environment is GLOBAL. Provide your own if in another environment
# Example environment is China, GLOBAL
# spring.cloud.azure.environment=[environment]

# Change into your containerName, blobName
blob=azure-blob://containerName/blobName

....

6. Start the `StorageApplication` Spring Boot app.
+
```
$ mvn spring-boot:run
```

7. Send a POST request to update file contents:
+
```
$ curl -d 'new message' -H 'Content-Type: text/plain' localhost:8080/blob
```
+
Verify by sending a GET request
+
```
$ curl -XGET http://localhost:8080/blob
```

8. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid unexpected charges.

== Examples
== Troubleshooting
== Next steps
== Contributing
