// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.machinelearning.implementation;

import com.azure.core.management.SystemData;
import com.azure.core.util.Context;
import com.azure.resourcemanager.machinelearning.fluent.models.RaiPolicyPropertiesBasicResourceInner;
import com.azure.resourcemanager.machinelearning.models.RaiPolicyProperties;
import com.azure.resourcemanager.machinelearning.models.RaiPolicyPropertiesBasicResource;

public final class RaiPolicyPropertiesBasicResourceImpl
    implements RaiPolicyPropertiesBasicResource, RaiPolicyPropertiesBasicResource.Definition {
    private RaiPolicyPropertiesBasicResourceInner innerObject;

    private final com.azure.resourcemanager.machinelearning.MachineLearningManager serviceManager;

    RaiPolicyPropertiesBasicResourceImpl(RaiPolicyPropertiesBasicResourceInner innerObject,
        com.azure.resourcemanager.machinelearning.MachineLearningManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String id() {
        return this.innerModel().id();
    }

    public String name() {
        return this.innerModel().name();
    }

    public String type() {
        return this.innerModel().type();
    }

    public RaiPolicyProperties properties() {
        return this.innerModel().properties();
    }

    public SystemData systemData() {
        return this.innerModel().systemData();
    }

    public RaiPolicyPropertiesBasicResourceInner innerModel() {
        return this.innerObject;
    }

    private com.azure.resourcemanager.machinelearning.MachineLearningManager manager() {
        return this.serviceManager;
    }

    private String resourceGroupName;

    private String workspaceName;

    private String endpointName;

    private String raiPolicyName;

    public RaiPolicyPropertiesBasicResourceImpl withExistingEndpoint(String resourceGroupName, String workspaceName,
        String endpointName) {
        this.resourceGroupName = resourceGroupName;
        this.workspaceName = workspaceName;
        this.endpointName = endpointName;
        return this;
    }

    public RaiPolicyPropertiesBasicResource create() {
        this.innerObject = serviceManager.serviceClient()
            .getRaiPolicies()
            .create(resourceGroupName, workspaceName, endpointName, raiPolicyName, this.innerModel(), Context.NONE);
        return this;
    }

    public RaiPolicyPropertiesBasicResource create(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getRaiPolicies()
            .create(resourceGroupName, workspaceName, endpointName, raiPolicyName, this.innerModel(), context);
        return this;
    }

    RaiPolicyPropertiesBasicResourceImpl(String name,
        com.azure.resourcemanager.machinelearning.MachineLearningManager serviceManager) {
        this.innerObject = new RaiPolicyPropertiesBasicResourceInner();
        this.serviceManager = serviceManager;
        this.raiPolicyName = name;
    }

    public RaiPolicyPropertiesBasicResource refresh() {
        this.innerObject = serviceManager.serviceClient()
            .getRaiPolicies()
            .getWithResponse(resourceGroupName, workspaceName, endpointName, raiPolicyName, Context.NONE)
            .getValue();
        return this;
    }

    public RaiPolicyPropertiesBasicResource refresh(Context context) {
        this.innerObject = serviceManager.serviceClient()
            .getRaiPolicies()
            .getWithResponse(resourceGroupName, workspaceName, endpointName, raiPolicyName, context)
            .getValue();
        return this;
    }

    public RaiPolicyPropertiesBasicResourceImpl withProperties(RaiPolicyProperties properties) {
        this.innerModel().withProperties(properties);
        return this;
    }
}
