# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/servicegroups/ci.yml
      - sdk/servicegroups/azure-resourcemanager-servicegroups/
    exclude:
      - sdk/servicegroups/pom.xml
      - sdk/servicegroups/azure-resourcemanager-servicegroups/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/servicegroups/ci.yml
      - sdk/servicegroups/azure-resourcemanager-servicegroups/
    exclude:
      - sdk/servicegroups/pom.xml
      - sdk/servicegroups/azure-resourcemanager-servicegroups/pom.xml

parameters:
  - name: release_azureresourcemanagerservicegroups
    displayName: azure-resourcemanager-servicegroups
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: servicegroups
    Artifacts:
      - name: azure-resourcemanager-servicegroups
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerservicegroups
        releaseInBatch: ${{ parameters.release_azureresourcemanagerservicegroups }}
