// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.hybridcompute.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Indicates which kind of Arc machine placement on-premises, such as HCI, SCVMM or VMware etc.
 */
public final class ArcKindEnum extends ExpandableStringEnum<ArcKindEnum> {
    /**
     * AVS.
     */
    public static final ArcKindEnum AVS = fromString("AVS");

    /**
     * HCI.
     */
    public static final ArcKindEnum HCI = fromString("HCI");

    /**
     * SCVMM.
     */
    public static final ArcKindEnum SCVMM = fromString("SCVMM");

    /**
     * VMware.
     */
    public static final ArcKindEnum VMWARE = fromString("VMware");

    /**
     * EPS.
     */
    public static final ArcKindEnum EPS = fromString("EPS");

    /**
     * GCP.
     */
    public static final ArcKindEnum GCP = fromString("GCP");

    /**
     * AWS.
     */
    public static final ArcKindEnum AWS = fromString("AWS");

    /**
     * Creates a new instance of ArcKindEnum value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public ArcKindEnum() {
    }

    /**
     * Creates or finds a ArcKindEnum from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ArcKindEnum.
     */
    public static ArcKindEnum fromString(String name) {
        return fromString(name, ArcKindEnum.class);
    }

    /**
     * Gets known ArcKindEnum values.
     * 
     * @return known ArcKindEnum values.
     */
    public static Collection<ArcKindEnum> values() {
        return values(ArcKindEnum.class);
    }
}
