blob.accountName=sideshowcodersdktest
blob.accountKey=fSGDmPYIyrdP3i3gKMwpDwhv4jFdnQ8dYov6kJ3jz+eCekTukHMec2R+Q5nyJdb4z6eJNioYsazWTtH+K9FwAg==
blob.uri=http://sideshowcodersdktest.blob.core.windows.net
queue.accountName=sideshowcodersdktest
queue.accountKey=fSGDmPYIyrdP3i3gKMwpDwhv4jFdnQ8dYov6kJ3jz+eCekTukHMec2R+Q5nyJdb4z6eJNioYsazWTtH+K9FwAg==
queue.uri=http://sideshowcodersdktest.queue.core.windows.net
table.accountName=sideshowcodersdktest
table.accountKey=fSGDmPYIyrdP3i3gKMwpDwhv4jFdnQ8dYov6kJ3jz+eCekTukHMec2R+Q5nyJdb4z6eJNioYsazWTtH+K9FwAg==
table.uri=http://sideshowcodersdktest.table.core.windows.net
serviceBus.uri=https://sideshowcodersdktest.servicebus.windows.net/
serviceBus.wrap.uri=https://sideshowcodersdktest-sb.accesscontrol.windows.net/WRAPv0.9
serviceBus.wrap.name=RootManageSharedAccessKey
serviceBus.wrap.password=PD6rXxZOjLZM0awHEegVd/zUWqcwyalAuACcCx4rENA=
serviceBus.connection.string=EndPoint=sb://%SERVICEBUS_NAMESPACE%.servicebus.windows.net/;SharedSecretIssuer=RootManageSharedAccessKey;SharedSecretValue=PD6rXxZOjLZM0awHEegVd/zUWqcwyalAuACcCx4rENA=
media.uri=https://media.windows.net/API/
media.oauth.uri=https://wamsprodglobal001acs.accesscontrol.windows.net/v2/OAuth2-13
media.oauth.client.id=sideshowcodersdktest
media.oauth.client.secret=VeraY+w72BZipNrQe+iiKNezeq5UCjNCkLw8RwbHedA=
media.oauth.scope=urn:WindowsAzureMediaServices
management.uri=https://management.core.windows.net/
management.keystore.path=/Users/phil/Source/azure-sdk-for-java/sideshowcodersdktest.jks
management.keystore.password=ph1lf3hr3
management.subscription.id=4aeabf2a-8cb7-4d0e-9633-d5dc5470a32a
management.keystore.type=jks


serviceBus.uri=https://%SERVICEBUS_NAMESPACE%.servicebus.windows.net/
serviceBus.wrap.uri=https://%SERVICEBUS_NAMESPACE%-sb.accesscontrol.windows.net/WRAPv0.9
serviceBus.wrap.name=%SERVICEBUS_SERVICEIDENTITY%
serviceBus.wrap.password=%SERVICEBUS_SHAREDSECRET%
serviceBus.connection.string=EndPoint=sb://%SERVICEBUS_NAMESPACE%.servicebus.windows.net/;SharedSecretIssuer=%SERVICEBUS_SERVICEIDENTITY%;SharedSecretValue=%SERVICEBUS_SHAREDSECRET%
blob.accountName=%BLOB_ACCOUNTNAME%
blob.accountKey=%BLOB_ACCOUNTKEY%
blob.uri=http://%BLOB_ACCOUNTNAME%.blob.core.windows.net
queue.accountName=%QUEUE_ACCOUNTNAME%
queue.accountKey=%QUEUE_ACCOUNTKEY%
queue.uri=http://%QUEUE_ACCOUNTNAME%.queue.core.windows.net
table.accountName=%TABLE_ACCOUNTNAME%
table.accountKey=%TABLE_ACCOUNTKEY%
table.uri=http://%TABLE_ACCOUNTNAME%.table.core.windows.net
media.uri=%MEDIA.URI%
media.oauth.uri=%MEDIA.OAUTH.URI%
media.oauth.client.id=%OMEDIA.AUTH.CLIENT.ID%
media.oauth.client.secret=%MEDIA.OAUTH.CLIENT.SECRET%
media.oauth.scope=urn:WindowsAzureMediaServices
management.keystore.path=%MANAGEMENT.KEYSTORE.PATH%
management.keystore.password=%MANAGEMENT.KEYSTORE.PASSWORD%
management.keystore.type=%MANAGEMENT.KEYSTORE.TYPE%
management.subscription.id=%MANAGEMENT.SUBSCRIPTION.ID%
management.uri=%MANAGEMENT.URI%

