
SPRING_BOOT_MAJOR_2_VERSION_NAME = '2'
SPRING_BOOT_MAJOR_2_VERSION_TAG_PREFIX = ''
SPRING_BOOT_MAJOR_3_VERSION_NAME = '3'
SPRING_BOOT_MAJOR_3_VERSION_TAG_PREFIX = 'springboot3_'
SPRING_BOOT_MAJOR_VERSION_PREFIX_DICT = {
    SPRING_BOOT_MAJOR_2_VERSION_NAME: SPRING_BOOT_MAJOR_2_VERSION_TAG_PREFIX,
    SPRING_BOOT_MAJOR_3_VERSION_NAME: SPRING_BOOT_MAJOR_3_VERSION_TAG_PREFIX
}


def get_spring_boot_version_tag_prefix(spring_boot_version):
    if spring_boot_version.startswith('3.') or spring_boot_version == SPRING_BOOT_MAJOR_3_VERSION_NAME:
        return SPRING_BOOT_MAJOR_VERSION_PREFIX_DICT[SPRING_BOOT_MAJOR_3_VERSION_NAME]
    elif spring_boot_version.startswith('2.') or spring_boot_version == SPRING_BOOT_MAJOR_2_VERSION_NAME:
        return SPRING_BOOT_MAJOR_VERSION_PREFIX_DICT[SPRING_BOOT_MAJOR_2_VERSION_NAME]
    else:
        return ''
