Args=\
  -H:+AddAllCharsets \
  -H:+ReportExceptionStackTraces \
  --initialize-at-build-time=com.fasterxml.jackson.core.Base64Variants,\
                             com.fasterxml.jackson.core.JsonFactory,\
                             com.fasterxml.jackson.core.io.CharTypes,\
                             com.fasterxml.jackson.core.io.JsonStringEncoder,\
                             com.fasterxml.jackson.core.io.SerializedString,\
                             com.fasterxml.jackson.databind.MappingJsonFactory

