// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.hybridnetwork.fluent.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The device registration key. */
@Immutable
public final class DeviceRegistrationKeyInner {
    /*
     * The registration key for the device.
     */
    @JsonProperty(value = "registrationKey", access = JsonProperty.Access.WRITE_ONLY)
    private String registrationKey;

    /**
     * Get the registrationKey property: The registration key for the device.
     *
     * @return the registrationKey value.
     */
    public String registrationKey() {
        return this.registrationKey;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
