// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.messaging.servicebus.administration.implementation.models;

import com.azure.core.annotation.Immutable;
import com.azure.xml.XmlReader;
import com.azure.xml.XmlWriter;
import javax.xml.stream.XMLStreamException;

/** The EmptyRuleAction model. */
@Immutable
public final class EmptyRuleActionImpl extends RuleActionImpl {
    /*
     * The type property.
     */
    private static final String TYPE = "EmptyRuleAction";

    /** Creates an instance of EmptyRuleAction class. */
    public EmptyRuleActionImpl() {}

    @Override
    public XmlWriter toXml(XmlWriter xmlWriter) throws XMLStreamException {
        xmlWriter.writeStartElement("EmptyRuleAction");
        xmlWriter.writeStringAttribute("http://www.w3.org/2001/XMLSchema-instance", "type", TYPE);
        return xmlWriter.writeEndElement();
    }

    /**
     * Reads an instance of EmptyRuleAction from the XmlReader.
     *
     * @param xmlReader The XmlReader being read.
     * @return An instance of EmptyRuleAction if the XmlReader was pointing to an instance of it, or null if it was
     *     pointing to XML null.
     * @throws IllegalStateException If the deserialized XML object was missing the polymorphic discriminator.
     */
    public static EmptyRuleActionImpl fromXml(XmlReader xmlReader) throws XMLStreamException {
        return xmlReader.readObject(
                "EmptyRuleAction",
                reader -> {
                    String type = reader.getStringAttribute("http://www.w3.org/2001/XMLSchema-instance", "type");
                    if (!"EmptyRuleAction".equals(type)) {
                        throw new IllegalStateException(
                                "'type' was expected to be non-null and equal to 'EmptyRuleAction'. The found 'type' was '"
                                        + type
                                        + "'.");
                    }
                    EmptyRuleActionImpl deserializedEmptyRuleActionImpl = new EmptyRuleActionImpl();

                    return deserializedEmptyRuleActionImpl;
                });
    }
}
