// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.mongodbatlas.models;

import com.azure.core.annotation.Fluent;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * Properties specific to a MongoDB Atlas Cluster.
 */
@Fluent
public final class ClusterProperties implements JsonSerializable<ClusterProperties> {
    /*
     * Name of the MongoDB Atlas Cluster.
     */
    private String clusterName;

    /*
     * Cluster tier (FREE, FLEX, M10, M30).
     */
    private ClusterTier clusterTier;

    /*
     * Azure region where the cluster is deployed.
     */
    private String regionName;

    /*
     * MongoDB version running on the cluster.
     */
    private String mongoDbVersion;

    /*
     * Whether backups are active for the cluster; null if undetermined.
     */
    private Boolean backups;

    /*
     * Current state of the cluster.
     */
    private String state;

    /*
     * Provisioning state of the resource.
     */
    private ResourceProvisioningState provisioningState;

    /**
     * Creates an instance of ClusterProperties class.
     */
    public ClusterProperties() {
    }

    /**
     * Get the clusterName property: Name of the MongoDB Atlas Cluster.
     * 
     * @return the clusterName value.
     */
    public String clusterName() {
        return this.clusterName;
    }

    /**
     * Get the clusterTier property: Cluster tier (FREE, FLEX, M10, M30).
     * 
     * @return the clusterTier value.
     */
    public ClusterTier clusterTier() {
        return this.clusterTier;
    }

    /**
     * Set the clusterTier property: Cluster tier (FREE, FLEX, M10, M30).
     * 
     * @param clusterTier the clusterTier value to set.
     * @return the ClusterProperties object itself.
     */
    public ClusterProperties withClusterTier(ClusterTier clusterTier) {
        this.clusterTier = clusterTier;
        return this;
    }

    /**
     * Get the regionName property: Azure region where the cluster is deployed.
     * 
     * @return the regionName value.
     */
    public String regionName() {
        return this.regionName;
    }

    /**
     * Set the regionName property: Azure region where the cluster is deployed.
     * 
     * @param regionName the regionName value to set.
     * @return the ClusterProperties object itself.
     */
    public ClusterProperties withRegionName(String regionName) {
        this.regionName = regionName;
        return this;
    }

    /**
     * Get the mongoDbVersion property: MongoDB version running on the cluster.
     * 
     * @return the mongoDbVersion value.
     */
    public String mongoDbVersion() {
        return this.mongoDbVersion;
    }

    /**
     * Get the backups property: Whether backups are active for the cluster; null if undetermined.
     * 
     * @return the backups value.
     */
    public Boolean backups() {
        return this.backups;
    }

    /**
     * Get the state property: Current state of the cluster.
     * 
     * @return the state value.
     */
    public String state() {
        return this.state;
    }

    /**
     * Get the provisioningState property: Provisioning state of the resource.
     * 
     * @return the provisioningState value.
     */
    public ResourceProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("clusterTier", this.clusterTier == null ? null : this.clusterTier.toString());
        jsonWriter.writeStringField("regionName", this.regionName);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of ClusterProperties from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of ClusterProperties if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the ClusterProperties.
     */
    public static ClusterProperties fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            ClusterProperties deserializedClusterProperties = new ClusterProperties();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("clusterTier".equals(fieldName)) {
                    deserializedClusterProperties.clusterTier = ClusterTier.fromString(reader.getString());
                } else if ("regionName".equals(fieldName)) {
                    deserializedClusterProperties.regionName = reader.getString();
                } else if ("clusterName".equals(fieldName)) {
                    deserializedClusterProperties.clusterName = reader.getString();
                } else if ("mongoDbVersion".equals(fieldName)) {
                    deserializedClusterProperties.mongoDbVersion = reader.getString();
                } else if ("backups".equals(fieldName)) {
                    deserializedClusterProperties.backups = reader.getNullable(JsonReader::getBoolean);
                } else if ("state".equals(fieldName)) {
                    deserializedClusterProperties.state = reader.getString();
                } else if ("provisioningState".equals(fieldName)) {
                    deserializedClusterProperties.provisioningState
                        = ResourceProvisioningState.fromString(reader.getString());
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedClusterProperties;
        });
    }
}
