// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.
package com.azure.compute.batch.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;
import java.util.List;

/**
 * An error encountered by a Compute Node.
 */
@Immutable
public final class BatchNodeError implements JsonSerializable<BatchNodeError> {

    /*
     * An identifier for the Compute Node error. Codes are invariant and are intended to be consumed programmatically.
     */
    @Generated
    private String code;

    /*
     * A message describing the Compute Node error, intended to be suitable for display in a user interface.
     */
    @Generated
    private String message;

    /*
     * The list of additional error details related to the Compute Node error.
     */
    @Generated
    private List<NameValuePair> errorDetails;

    /**
     * Creates an instance of BatchNodeError class.
     */
    @Generated
    private BatchNodeError() {
    }

    /**
     * Get the code property: An identifier for the Compute Node error. Codes are invariant and are intended to be
     * consumed programmatically.
     *
     * @return the code value.
     */
    @Generated
    public String getCode() {
        return this.code;
    }

    /**
     * Get the message property: A message describing the Compute Node error, intended to be suitable for display in a
     * user interface.
     *
     * @return the message value.
     */
    @Generated
    public String getMessage() {
        return this.message;
    }

    /**
     * Get the errorDetails property: The list of additional error details related to the Compute Node error.
     *
     * @return the errorDetails value.
     */
    @Generated
    public List<NameValuePair> getErrorDetails() {
        return this.errorDetails;
    }

    /**
     * {@inheritDoc}
     */
    @Generated
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("code", this.code);
        jsonWriter.writeStringField("message", this.message);
        jsonWriter.writeArrayField("errorDetails", this.errorDetails, (writer, element) -> writer.writeJson(element));
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of BatchNodeError from the JsonReader.
     *
     * @param jsonReader The JsonReader being read.
     * @return An instance of BatchNodeError if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IOException If an error occurs while reading the BatchNodeError.
     */
    @Generated
    public static BatchNodeError fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            BatchNodeError deserializedBatchNodeError = new BatchNodeError();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();
                if ("code".equals(fieldName)) {
                    deserializedBatchNodeError.code = reader.getString();
                } else if ("message".equals(fieldName)) {
                    deserializedBatchNodeError.message = reader.getString();
                } else if ("errorDetails".equals(fieldName)) {
                    List<NameValuePair> errorDetails = reader.readArray(reader1 -> NameValuePair.fromJson(reader1));
                    deserializedBatchNodeError.errorDetails = errorDetails;
                } else {
                    reader.skipChildren();
                }
            }
            return deserializedBatchNodeError;
        });
    }
}
