// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.azure.spring.cloud.autoconfigure.context;

/**
 *
 */
public abstract class AzureContextUtils {

    public static final String DEFAULT_TOKEN_CREDENTIAL_BEAN_NAME = "springDefaultAzureCredential";

    public static final String EVENT_HUB_CONSUMER_CLIENT_BUILDER_FACTORY_BEAN_NAME =
        "EVENT_HUB_CONSUMER_CLIENT_BUILDER_FACTORY_BEAN_NAME";
    public static final String EVENT_HUB_CONSUMER_CLIENT_BUILDER_BEAN_NAME =
        "EVENT_HUB_CONSUMER_CLIENT_BUILDER_BEAN_NAME";

    public static final String EVENT_HUB_PRODUCER_CLIENT_BUILDER_FACTORY_BEAN_NAME =
        "EVENT_HUB_PRODUCER_CLIENT_BUILDER_FACTORY_BEAN_NAME";
    public static final String EVENT_HUB_PRODUCER_CLIENT_BUILDER_BEAN_NAME =
        "EVENT_HUB_PRODUCER_CLIENT_BUILDER_BEAN_NAME";

    public static final String AZURE_GLOBAL_PROPERTY_BEAN_NAME =
        "AZURE_GLOBAL_PROPERTY_BEAN_NAME";

    public static final String EVENT_HUB_PROCESSOR_CHECKPOINT_STORE_STORAGE_CLIENT_BUILDER_BEAN_NAME =
        "EVENT_HUB_PROCESSOR_CHECKPOINT_STORE_STORAGE_CLIENT_BUILDER_BEAN_NAME";

    public static final String STORAGE_BLOB_SERVICE_CLIENT_BUILDER_BEAN_NAME =
        "STORAGE_BLOB_SERVICE_CLIENT_BUILDER_BEAN_NAME";

    public static final String CONFIGURATION_BUILDER_BEAN_NAME = "CONFIGURATION_BUILDER_BEAN_NAME";
    public static final String CONFIGURATION_BUILDER_FOR_INTEGRATION_BEAN_NAME = "CONFIGURATION_BUILDER_FOR_INTEGRATION_BEAN_NAME";

}
