/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.recoveryservices.backup.v2016_06_01;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for JobOperationType.
 */
public enum JobOperationType {
    /** Enum value Invalid. */
    INVALID("Invalid"),

    /** Enum value ConfigureBackup. */
    CONFIGURE_BACKUP("ConfigureBackup"),

    /** Enum value Backup. */
    BACKUP("Backup"),

    /** Enum value Restore. */
    RESTORE("Restore"),

    /** Enum value DisableBackup. */
    DISABLE_BACKUP("DisableBackup"),

    /** Enum value DeleteBackupData. */
    DELETE_BACKUP_DATA("DeleteBackupData");

    /** The actual serialized value for a JobOperationType instance. */
    private String value;

    JobOperationType(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a JobOperationType instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed JobOperationType object, or null if unable to parse.
     */
    @JsonCreator
    public static JobOperationType fromString(String value) {
        JobOperationType[] items = JobOperationType.values();
        for (JobOperationType item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
