// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.reservations.models;

import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Status of the operation.
 */
public final class ExchangeOperationResultStatus extends ExpandableStringEnum<ExchangeOperationResultStatus> {
    /**
     * Succeeded.
     */
    public static final ExchangeOperationResultStatus SUCCEEDED = fromString("Succeeded");

    /**
     * Failed.
     */
    public static final ExchangeOperationResultStatus FAILED = fromString("Failed");

    /**
     * Cancelled.
     */
    public static final ExchangeOperationResultStatus CANCELLED = fromString("Cancelled");

    /**
     * PendingRefunds.
     */
    public static final ExchangeOperationResultStatus PENDING_REFUNDS = fromString("PendingRefunds");

    /**
     * PendingPurchases.
     */
    public static final ExchangeOperationResultStatus PENDING_PURCHASES = fromString("PendingPurchases");

    /**
     * Creates a new instance of ExchangeOperationResultStatus value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Deprecated
    public ExchangeOperationResultStatus() {
    }

    /**
     * Creates or finds a ExchangeOperationResultStatus from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ExchangeOperationResultStatus.
     */
    public static ExchangeOperationResultStatus fromString(String name) {
        return fromString(name, ExchangeOperationResultStatus.class);
    }

    /**
     * Gets known ExchangeOperationResultStatus values.
     * 
     * @return known ExchangeOperationResultStatus values.
     */
    public static Collection<ExchangeOperationResultStatus> values() {
        return values(ExchangeOperationResultStatus.class);
    }
}
