# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - eng/scripts/*
      - eng/pipelines/scripts/Invoke-Sparse-Checkout.ps1
      - eng/pipelines/templates/steps/sparse-checkout-repo-initialized.yml
    exclude:
      - eng/scripts/typespec

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - eng/scripts/*
      - eng/pipelines/scripts/Invoke-Sparse-Checkout.ps1
      - eng/pipelines/templates/steps/sparse-checkout-repo-initialized.yml

extends:
  template: /eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
  parameters:
    TargetDirectory: eng/scripts/
    TargetTags: 'UnitTest'
