#!/bin/sh

# Validate library versions
pwsh eng/versioning/pom_file_version_scanner.ps1

changed_files=$(git diff --name-only)

for file in $changed_files; do
    pwsh eng/common/spelling/Invoke-Cspell.ps1 $file
done
