# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerservicenodecustomization/ci.yml
      - sdk/containerservicenodecustomization/azure-resourcemanager-containerservicenodecustomization/
    exclude:
      - sdk/containerservicenodecustomization/pom.xml
      - sdk/containerservicenodecustomization/azure-resourcemanager-containerservicenodecustomization/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/containerservicenodecustomization/ci.yml
      - sdk/containerservicenodecustomization/azure-resourcemanager-containerservicenodecustomization/
    exclude:
      - sdk/containerservicenodecustomization/pom.xml
      - sdk/containerservicenodecustomization/azure-resourcemanager-containerservicenodecustomization/pom.xml

parameters:
  - name: release_azureresourcemanagercontainerservicenodecustomization
    displayName: azure-resourcemanager-containerservicenodecustomization
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: containerservicenodecustomization
    Artifacts:
      - name: azure-resourcemanager-containerservicenodecustomization
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagercontainerservicenodecustomization
        releaseInBatch: ${{ parameters.release_azureresourcemanagercontainerservicenodecustomization }}
