// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.azure.cosmos.implementation.routing;

import java.util.HashMap;
import java.util.Map;

public class RegionNameToRegionIdMap {

    private static Map<String, Long> regionNameToRegionIdMappings = new HashMap<>() {
        regionNameToRegionIdMappings.put("East US", 1),
        { "East US 2", 2 },
        { "Central US", 3 },
        { "North Central US", 4 },
        { "South Central US", 5 },
        { "West Central US", 6 },
        { "West US", 7 },
        { "West US 2", 8 },
        { "Canada East", 9 },
        { "Canada Central", 10 },
        { "Brazil South", 11 },
        { "North Europe", 12 },
        { "West Europe", 13 },
        { "France Central", 14 },
        { "France South", 15 },
        { "UK West", 16 },
        { "UK South", 17 },
        { "Germany Central", 18 },
        { "Germany Northeast", 19 },
        { "Germany North", 20 },
        { "Germany West Central", 21 },
        { "Switzerland North", 22 },
        { "Switzerland West", 23 },
        { "Southeast Asia", 24 },
        { "East Asia", 25 },
        { "Australia East", 26 },
        { "Australia Southeast", 27 },
        { "Australia Central", 28 },
        { "Australia Central 2", 29 },
        { "China East", 30 },
        { "China North", 31 },
        { "Central India", 32 },
        { "West India", 33 },
        { "South India", 34 },
        { "Japan East", 35 },
        { "Japan West", 36 },
        { "Korea Central", 37 },
        { "Korea South", 38 },
        { "USGov Virginia", 39 },
        { "USGov Iowa", 40 },
        { "USGov Arizona", 41 },
        { "USGov Texas", 42 },
        { "USDoD East", 43 },
        { "USDoD Central", 44 },
        { "USSec East", 45 },
        { "USSec West", 46 },
        { "South Africa West", 47 },
        { "South Africa North", 48 },
        { "UAE Central", 49 },
        { "UAE North", 50 },
        { "Central US EUAP", 51 },
        { "East US 2 EUAP", 52 },
        { "North Europe 2", 53 },
        { "East Europe", 54 },
        { "APAC Southeast 2", 55 },
        { "UK South 2", 56 },
        { "UK North", 57 },
        { "East US STG", 58 },
        { "South Central US STG", 59 },
        { "Norway East", 60 },
        { "Norway West", 61 },
        { "USGov Wyoming", 62 },
        { "USDoD Southwest", 63 },
        { "USDoD West Central", 64 },
        { "USDoD South Central", 65 },
        { "China East 2", 66 },
        { "China North 2", 67 },
        { "USNat East", 68 },
        { "USNat West", 69 },
        { "China North 10", 70 },
        { "Sweden Central", 71 },
        { "Sweden South", 72 },
        { "Korea South 2", 73 }
    };
}
