== Spring Cloud Azure Test cases document

=== Test scenario analysis

.Test scenario
[width=10%, cols="^~,20%,20%,20%,~,^~,~", options="header"]
|===
| Category | Scenario | Test Step | Expected Result | How Spring test such case? | Is UT enough?  | Current use cases
|Storage blob, Indicator
| *Test blob health indicator returns the up state*

The Azure actuator starter should work well with storage blob indicator when using Azure storage blob starter, the blob status should be healthy.
|
1. Add `spring-cloud-azure-starter-storage-blob` and `spring-cloud-azure-starter-actuator` dependencies. +
2. Configure the below combinations for storage blob properties. +

[source, yaml]
----
# Resource location
blob: azure-blob://test/test-blob
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

|
1. The blob health indicator bean should be configured. +
2. The up status should be returned from the storage blob health endpoint. +
|There are 2 UTs for reference. +
1. https://github.com/moarychan/spring-boot/blob/dac63fc3e52ecb36677965b97b96ebbf1a7871c8/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/redis/RedisHealthContributorAutoConfigurationTests.java#L44[RedisHealthContributorAutoConfigurationTests] in spring-boot-actuator-autoconfigure +
Use `ApplicationContextRunner`  with Redis related auto-configuration to validate the bean creation. +
2. https://github.com/moarychan/spring-boot/blob/49baacbc1cb02a59efce1fe1698166de92d41d67/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/redis/RedisHealthIndicatorTests.java#L50[RedisHealthIndicatorTests] in spring-boot-actuator +
Mock `RedisConnection` and `RedisConnectionFactory` to make the redis connection's `info` method return pre-defined data, the status of the `Health` will be up.
|Yes
|https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageActuatorIT.java#L25[testBlobStorageActuatorHealth]


|Storage blob, Indicator
| *Test blob health indicator returns the down state*

The Azure actuator starter should work well with storage blob indicator when using Azure storage blob starter, the blob status should be down when blob service client does not respond data normally.
|
1. Add `spring-cloud-azure-starter-storage-blob` and `spring-cloud-azure-starter-actuator` dependencies. +
2. Configure the below combinations for storage blob properties. +
[source, yaml]
----
# Resource location
blob: azure-blob://test/test-blob
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

|
1. The blob health indicator bean should be configured. +
2. The application should start up normally.
2. The down status should be returned from the storage blob health endpoint. +
|There are 2 UTs for reference. +
1. https://github.com/moarychan/spring-boot/blob/dac63fc3e52ecb36677965b97b96ebbf1a7871c8/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/redis/RedisHealthContributorAutoConfigurationTests.java#L44[RedisHealthContributorAutoConfigurationTests] in spring-boot-actuator-autoconfigure +
Use `ApplicationContextRunner`  with Redis related auto-configuration to validate the bean creation. +
2. https://github.com/moarychan/spring-boot/blob/49baacbc1cb02a59efce1fe1698166de92d41d67/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/redis/RedisHealthIndicatorTests.java#L62[RedisHealthIndicatorTests] in spring-boot-actuator +
Mock `RedisConnection` and `RedisConnectionFactory` to make the redis connection's `info` method return pre-defined data, the status of the `Health` will be down.
|Yes
|N/A


|Storage fileshare, Indicator
| *Test fileshare health indicator returns the up state*

The Azure actuator starter should work well with storage fileshare indicator when using Azure storage fileshare starter, the fileshare status should be healthy.
|
1. Add `spring-cloud-azure-starter-storage-fileshare` and `spring-cloud-azure-starter-actuator` dependencies. +
2. Configure the below combinations for storage fileshare properties. +

[source,yaml]
----
# Resource location
blob: azure-file://test/test-file
spring:
  cloud:
    azure:
      storage:
        fileshare:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

|
1. The fileshare health indicator bean should be configured. +
2. The up status should be returned from the storage filesahre health endpoint. +
|Same with above
|Yes
|https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageActuatorIT.java#L54[testFileStorageActuatorHealth]


| Storage Blob, Data Plan
| *Use storage blob starter dependency to write and read data*

Use Azure storage blob dependency to write, then read the testing data normally.
|
1. Add `spring-cloud-azure-starter-storage-blob` dependency. +
2. Configure the below combinations for storage blob properties. +

[source,properties]
----
spring.cloud.azure.storage.blob.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.blob.account-key=${AZURE_STORAGE_ACCOUNT_KEY}
spring.cloud.azure.storage.blob.endpoint=${AZURE_STORAGE_BLOB_ENDPOINT}
my-blob=${AZURE_STORAGE_BLOB}
----

|
1. The data for the testing resource should be written in Azure Storage Blob service successfully. +
2. The read data from Azure Storage Blob service should be the same with testing resources. +
|There are 3 UTs for reference. +
1. https://github.com/moarychan/spring-framework/blob/c8f430ee9188ad082bf76e5b05877d00bafe1a82/spring-core/src/test/java/org/springframework/core/io/support/PathMatchingResourcePatternResolverTests.java#L69[PathMatchingResourcePatternResolverTests] in spring-core +
Resolve the `azure-blob:xxx` resource using `AzureStorageBlobProtocolResolver`, confirm that the actual resource type is `StorageBlobResource`, and the others properties are the same with the testing resource. +
2. Same with `RedisHealthContributorAutoConfigurationTests` test class to validate the storage blob resolver bean creation. +
3. https://github.com/moarychan/spring-boot/blob/4009acf025b3a6926c6eeedd38618d2fd67210cc/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/cache/CacheAutoConfigurationTests.java#L274[CacheAutoConfigurationTests] in spring-boot-autoconfigure
Configure necessary properties, and validate bean creations from `RedisCacheConfiguration`.
| Yes
| https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageWriteIT.java#L28[testWriteBlobStorage]


| Storage Fileshare, Data Plan
| *Use storage fileshare starter dependency to write and read data*

Use Azure file share starter dependency to write, then read the testing data normally.
|
1. Add `spring-cloud-azure-starter-storage-fileshare` dependency. +
2. Configure the below combinations for storage fileshare properties. +

[source,properties]
----
spring.cloud.azure.storage.fileshare.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.fileshare.account-key=${AZURE_STORAGE_ACCOUNT_KEY}
spring.cloud.azure.storage.fileshare.endpoint=${AZURE_STORAGE_FILE_ENDPOINT}
my-file=${AZURE_STORAGE_FILE}
----
|
1. The data for the testing resource should be written in Azure Storage file service successfully. +
2. The read data from Azure Storage File service should be the same with testing resources. +
|Same with above
| Yes
| https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageWriteIT.java#39[testWriteFileStorage]


|===
