= Spring Cloud Azure Test cases Scenarios


== Test blob health indicator returns the up state
The Azure actuator starter should work well with storage blob indicator when using Azure storage blob starter, the storage blob status should be healthy.

=== Tags
Storage blob, Indicator

=== Test Prerequisites
* Azure Storage Blob instance exists. +

=== Steps
* Add `spring-cloud-azure-starter-storage-blob` and `spring-cloud-azure-starter-actuator` dependencies. +
* Configure the below combinations for storage blob properties. +
[source, yaml]
----
# Resource location
blob: azure-blob://test/test-blob
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

=== Expected Result
* The blob health indicator bean should be configured. +
* The up status should be returned from the storage blob health endpoint. +

=== How Spring test such case?
There are 2 UTs for reference:

* https://github.com/moarychan/spring-boot/blob/dac63fc3e52ecb36677965b97b96ebbf1a7871c8/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/redis/RedisHealthContributorAutoConfigurationTests.java#L44[RedisHealthContributorAutoConfigurationTests] in spring-boot-actuator-autoconfigure +
Use `ApplicationContextRunner`  with Redis related auto-configuration to validate the bean creation. +
* https://github.com/moarychan/spring-boot/blob/49baacbc1cb02a59efce1fe1698166de92d41d67/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/redis/RedisHealthIndicatorTests.java#L50[RedisHealthIndicatorTests] in spring-boot-actuator +
Mock `RedisConnection` and `RedisConnectionFactory` to make the redis connection's `info` method return pre-defined data, the status of the `Health` will be up.

=== Is UT enough?
Yes

=== Current use cases
https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageActuatorIT.java#L25[testBlobStorageActuatorHealth]

== Test blob health indicator returns the down state
The Azure actuator starter should work well with storage blob indicator when using Azure storage blob starter, the storage blob status should be down when blob service client does not respond data normally.

=== Tags
Storage blob, Indicator

=== Test Prerequisites
* Azure Storage Blob instance exists. +

=== Steps
* Add `spring-cloud-azure-starter-storage-blob` and `spring-cloud-azure-starter-actuator` dependencies. +
* Configure the below combinations for storage blob properties. +

[source, yaml]
----
# Resource location
blob: azure-blob://test/test-blob
spring:
  cloud:
    azure:
      storage:
        blob:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

=== Expected Result
* The blob health indicator bean should be configured. +
* The application should start up normally. +
* The down status should be returned from the storage blob health endpoint. +

=== How Spring test such case?
There are 2 UTs for reference:

* https://github.com/moarychan/spring-boot/blob/dac63fc3e52ecb36677965b97b96ebbf1a7871c8/spring-boot-project/spring-boot-actuator-autoconfigure/src/test/java/org/springframework/boot/actuate/autoconfigure/redis/RedisHealthContributorAutoConfigurationTests.java#L44[RedisHealthContributorAutoConfigurationTests] in spring-boot-actuator-autoconfigure +
Use `ApplicationContextRunner`  with Redis related auto-configuration to validate the bean creation. +
* https://github.com/moarychan/spring-boot/blob/49baacbc1cb02a59efce1fe1698166de92d41d67/spring-boot-project/spring-boot-actuator/src/test/java/org/springframework/boot/actuate/redis/RedisHealthIndicatorTests.java#L62[RedisHealthIndicatorTests] in spring-boot-actuator +
Mock `RedisConnection` and `RedisConnectionFactory` to make the redis connection's `info` method return pre-defined data, the status of the `Health` will be down.

=== Is UT enough?
Yes

=== Current use cases
N/A

== Test fileshare health indicator returns the up state
The Azure actuator starter should work well with storage fileshare indicator when using Azure storage fileshare starter, the storage fileshare status should be healthy.

=== Tags
Storage fileshare, Indicator

=== Test Prerequisites
* Azure Storage File instance exists. +

=== Steps
* Add `spring-cloud-azure-starter-storage-fileshare` and `spring-cloud-azure-starter-actuator` dependencies. +
* Configure the below combinations for storage fileshare properties. +

[source,yaml]
----
# Resource location
file: azure-file://test/test-file
spring:
  cloud:
    azure:
      storage:
        fileshare:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

=== Expected Result
* The fileshare health indicator bean should be configured. +
* The up status should be returned from the storage filesahre health endpoint. +

=== How Spring test such case?
Same with link:testcase-document.adoc#test-fileshare-health-indicator-returns-the-up-state[Test blob health indicator returns the up state]

=== Is UT enough?
Yes

=== Current use cases
https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageActuatorIT.java#L54[testFileStorageActuatorHealth]

== Test fileshare health indicator returns the down state
The Azure actuator starter should work well with storage fileshare indicator when using Azure storage fileshare starter, the storage file status should be down when file service client does not respond data normally.

=== Tags
Storage fileshare, Indicator

=== Test Prerequisites
* Azure Storage account instance exists. +

=== Steps
* Add `spring-cloud-azure-starter-storage-fileshare` and `spring-cloud-azure-starter-actuator` dependencies. +
* Configure the below combinations for storage fileshare properties. +

[source, yaml]
----
# Resource location
file: azure-file://test/test-file
spring:
  cloud:
    azure:
      storage:
        fileshare:
          account-name: XXX
          account-key: XXX
          endpoint: XXX
management:
  endpoint:
    health:
      show-details: always
----

=== Expected Result
* The fileshare health indicator bean should be configured. +
* The application should start up normally. +
* The down status should be returned from the storage fileshare health endpoint. +

=== How Spring test such case?
Same with link:testcase-document.adoc#test-blob-health-indicator-returns-the-down-state[Test blob health indicator returns the down state]

=== Is UT enough?
Yes

=== Current use cases
N/A

== Use storage blob starter dependency to write and read data
Use Azure storage blob dependency to write, then read the testing data normally.

=== Tags
Storage Blob, Data Plane

=== Test Prerequisites
* Azure Storage Blob instance exists. +

=== Steps
* Add `spring-cloud-azure-starter-storage-blob` dependency. +
* Configure the below combinations for storage blob properties. +

[source,properties]
----
spring.cloud.azure.storage.blob.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.blob.account-key=${AZURE_STORAGE_ACCOUNT_KEY}
spring.cloud.azure.storage.blob.endpoint=${AZURE_STORAGE_BLOB_ENDPOINT}
my-blob=${AZURE_STORAGE_BLOB}
----

=== Expected Result
* The beans of storage blob resolver, builder factory, service client should be configured. +
* The data for the testing resource should be written in Azure Storage Blob service successfully. +
* The read data from Azure Storage Blob service should be the same with testing resources. +

=== How Spring test such case?
There are 3 UTs for reference:

* https://github.com/moarychan/spring-framework/blob/c8f430ee9188ad082bf76e5b05877d00bafe1a82/spring-core/src/test/java/org/springframework/core/io/support/PathMatchingResourcePatternResolverTests.java#L69[PathMatchingResourcePatternResolverTests] in spring-core +
Resolve the `azure-blob:xxx` resource using `AzureStorageBlobProtocolResolver`, confirm that the actual resource type is `StorageBlobResource`, and the others properties are the same with the testing resource. +
* Same with `RedisHealthContributorAutoConfigurationTests` test class to validate the storage blob resolver bean creation. +
* https://github.com/moarychan/spring-boot/blob/4009acf025b3a6926c6eeedd38618d2fd67210cc/spring-boot-project/spring-boot-autoconfigure/src/test/java/org/springframework/boot/autoconfigure/cache/CacheAutoConfigurationTests.java#L274[CacheAutoConfigurationTests] in spring-boot-autoconfigure
Configure necessary properties, and validate bean creations from `RedisCacheConfiguration`.

=== Is UT enough?
Yes

=== Current use cases
https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageWriteIT.java#L28[testWriteBlobStorage]

== Use storage fileshare starter dependency to write and read data
Use Azure file share starter dependency to write, then read the testing data normally.

=== Tags
Storage Fileshare, Data Plane

=== Test Prerequisites
* Azure Storage File instance exists. +

=== Steps
* Add `spring-cloud-azure-starter-storage-fileshare` dependency. +
* Configure the below combinations for storage fileshare properties. +

[source,properties]
----
spring.cloud.azure.storage.fileshare.account-name=${AZURE_STORAGE_ACCOUNT_NAME}
spring.cloud.azure.storage.fileshare.account-key=${AZURE_STORAGE_ACCOUNT_KEY}
spring.cloud.azure.storage.fileshare.endpoint=${AZURE_STORAGE_FILE_ENDPOINT}
my-file=${AZURE_STORAGE_FILE}
----

=== Expected Result
* The beans of storage fileshare resolver, builder factory, service client should be configured. +
* The data for the testing resource should be written in Azure Storage file service successfully. +
* The read data from Azure Storage File service should be the same with testing resources. +

=== How Spring test such case?
Same with link:testcase-document.adoc#use-storage-blob-starter-dependency-to-write-and-read-data[Use storage blob starter dependency to write and read data]

=== Is UT enough?
Yes

=== Current use cases
https://github.com/Azure/azure-sdk-for-java/blob/8c6650a298b51cefe559c470b8f818bfa53a8992/sdk/spring/azure-spring-boot-test-storage/src/test/java/com/azure/spring/test/storage/StorageWriteIT.java#39[testWriteFileStorage]
