# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/widgetanalytics/ci.yml
      - sdk/widgetanalytics/azure-widget-analytics/
    exclude:
      - sdk/widgetanalytics/pom.xml
      - sdk/widgetanalytics/azure-widget-analytics/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/widgetanalytics/ci.yml
      - sdk/widgetanalytics/azure-widget-analytics/
    exclude:
      - sdk/widgetanalytics/pom.xml
      - sdk/widgetanalytics/azure-widget-analytics/pom.xml

parameters:
  - name: release_azurewidgetanalytics
    displayName: azure-widget-analytics
    type: boolean
    default: true

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: widgetanalytics
    Artifacts:
      - name: azure-widget-analytics
        groupId: com.azure
        safeName: azurewidgetanalytics
        releaseInBatch: ${{ parameters.release_azurewidgetanalytics }}
