= Spring Cloud Azure Service Bus Operation Code Sample shared library for Java

== Key concepts
== Getting started

This code sample demonstrates how to use
https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-integration-azure/spring-integration-servicebus/src/main/java/com/microsoft/azure/spring/integration/servicebus/topic/ServiceBusTopicOperation.java[Service Bus Topic Operation]
and https://github.com/Microsoft/spring-cloud-azure/blob/master/spring-integration-azure/spring-integration-servicebus/src/main/java/com/microsoft/azure/spring/integration/servicebus/queue/ServiceBusQueueOperation.java[Service Bus Queue Operation].

Running this sample will be charged by Azure.
You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

=== Connection string based usage

1. Create Azure Service Bus namespace, queue and topic.
Please see https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-namespace-portal[how to create].

2. Update link:src/main/resources/application.properties[application.properties]

+
....
# Fill service bus namespace connection string copied from portal
spring.cloud.azure.servicebus.connection-string=[servicebus-namespace-connection-string]
....

=== Credential file based usage

1. Create Azure credential file.
Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how
to create credential file]
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put credential file under `src/main/resources/`.

3. Create Azure Service Bus namespace, queue and topic.
Please see https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-create-namespace-portal[how to create].
Or enable auto create resources feature in link:src/main/resources/application.properties[application.properties]:
+
....
spring.cloud.azure.auto-create-resources=true

# Default environment is GLOBAL. Provide your own if in another environment
# Example environment is China, GLOBAL
# spring.cloud.azure.environment=[environment]
# Example region is westUS, northchina
spring.cloud.azure.region=[region]
....

4. Update link:src/main/resources/application.properties[application.properties] file
+
....
# Enter 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credential-file-path=[credential-file-path]
spring.cloud.azure.resource-group=[resource-group]

spring.cloud.azure.servicebus.namespace=[servicebus-namespace]
....

=== How to run

5. Update queue name in link:src/main/java/com/example/QueueController.java#L31[QueueController], topic name and subscription in
link:src/main/java/com/example/TopicController.java#L29[TopicController].

6. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

7. Send a POST request to service bus queue
+
....
$ curl -X POST localhost:8080/queues?message=hello
....

8. Verify in your app's logs that a similar message was posted:
+
....
New message received: 'hello'
Message 'hello' successfully checkpointed
....

9. Send a POST request to service bus topic
+
....
$ curl -X POST localhost:8080/topics?message=hello
....

10. Verify in your app's logs that a similar message was posted:
+
....
New message received: 'hello'
Message 'hello' successfully checkpointed
....

11. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid extra charges.

== Examples
== Troubleshooting
== Next steps
== Contributing
