# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/horizondb/ci.yml
      - sdk/horizondb/azure-resourcemanager-horizondb/
    exclude:
      - sdk/horizondb/pom.xml
      - sdk/horizondb/azure-resourcemanager-horizondb/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/horizondb/ci.yml
      - sdk/horizondb/azure-resourcemanager-horizondb/
    exclude:
      - sdk/horizondb/pom.xml
      - sdk/horizondb/azure-resourcemanager-horizondb/pom.xml

parameters:
  - name: release_azureresourcemanagerhorizondb
    displayName: azure-resourcemanager-horizondb
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: horizondb
    Artifacts:
      - name: azure-resourcemanager-horizondb
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerhorizondb
        releaseInBatch: ${{ parameters.release_azureresourcemanagerhorizondb }}
