// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.Resource;
import com.azure.core.management.SystemData;
import com.azure.json.JsonReader;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import com.azure.resourcemanager.agrifood.models.Identity;
import com.azure.resourcemanager.agrifood.models.ProvisioningState;
import com.azure.resourcemanager.agrifood.models.PublicNetworkAccess;
import com.azure.resourcemanager.agrifood.models.SensorIntegration;
import java.io.IOException;
import java.util.Map;

/**
 * FarmBeats ARM Resource.
 */
@Fluent
public final class FarmBeatsInner extends Resource {
    /*
     * Identity for the resource.
     */
    private Identity identity;

    /*
     * FarmBeats ARM Resource properties.
     */
    private FarmBeatsPropertiesInner innerProperties;

    /*
     * Azure Resource Manager metadata containing createdBy and modifiedBy information.
     */
    private SystemData systemData;

    /*
     * The type of the resource.
     */
    private String type;

    /*
     * The name of the resource.
     */
    private String name;

    /*
     * Fully qualified resource Id for the resource.
     */
    private String id;

    /**
     * Creates an instance of FarmBeatsInner class.
     */
    public FarmBeatsInner() {
    }

    /**
     * Get the identity property: Identity for the resource.
     * 
     * @return the identity value.
     */
    public Identity identity() {
        return this.identity;
    }

    /**
     * Set the identity property: Identity for the resource.
     * 
     * @param identity the identity value to set.
     * @return the FarmBeatsInner object itself.
     */
    public FarmBeatsInner withIdentity(Identity identity) {
        this.identity = identity;
        return this;
    }

    /**
     * Get the innerProperties property: FarmBeats ARM Resource properties.
     * 
     * @return the innerProperties value.
     */
    private FarmBeatsPropertiesInner innerProperties() {
        return this.innerProperties;
    }

    /**
     * Get the systemData property: Azure Resource Manager metadata containing createdBy and modifiedBy information.
     * 
     * @return the systemData value.
     */
    public SystemData systemData() {
        return this.systemData;
    }

    /**
     * Get the type property: The type of the resource.
     * 
     * @return the type value.
     */
    @Override
    public String type() {
        return this.type;
    }

    /**
     * Get the name property: The name of the resource.
     * 
     * @return the name value.
     */
    @Override
    public String name() {
        return this.name;
    }

    /**
     * Get the id property: Fully qualified resource Id for the resource.
     * 
     * @return the id value.
     */
    @Override
    public String id() {
        return this.id;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FarmBeatsInner withLocation(String location) {
        super.withLocation(location);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FarmBeatsInner withTags(Map<String, String> tags) {
        super.withTags(tags);
        return this;
    }

    /**
     * Get the instanceUri property: Uri of the FarmBeats instance.
     * 
     * @return the instanceUri value.
     */
    public String instanceUri() {
        return this.innerProperties() == null ? null : this.innerProperties().instanceUri();
    }

    /**
     * Get the provisioningState property: FarmBeats instance provisioning state.
     * 
     * @return the provisioningState value.
     */
    public ProvisioningState provisioningState() {
        return this.innerProperties() == null ? null : this.innerProperties().provisioningState();
    }

    /**
     * Get the sensorIntegration property: Sensor integration request model.
     * 
     * @return the sensorIntegration value.
     */
    public SensorIntegration sensorIntegration() {
        return this.innerProperties() == null ? null : this.innerProperties().sensorIntegration();
    }

    /**
     * Set the sensorIntegration property: Sensor integration request model.
     * 
     * @param sensorIntegration the sensorIntegration value to set.
     * @return the FarmBeatsInner object itself.
     */
    public FarmBeatsInner withSensorIntegration(SensorIntegration sensorIntegration) {
        if (this.innerProperties() == null) {
            this.innerProperties = new FarmBeatsPropertiesInner();
        }
        this.innerProperties().withSensorIntegration(sensorIntegration);
        return this;
    }

    /**
     * Get the publicNetworkAccess property: Property to allow or block public traffic for an Azure FarmBeats resource.
     * 
     * @return the publicNetworkAccess value.
     */
    public PublicNetworkAccess publicNetworkAccess() {
        return this.innerProperties() == null ? null : this.innerProperties().publicNetworkAccess();
    }

    /**
     * Set the publicNetworkAccess property: Property to allow or block public traffic for an Azure FarmBeats resource.
     * 
     * @param publicNetworkAccess the publicNetworkAccess value to set.
     * @return the FarmBeatsInner object itself.
     */
    public FarmBeatsInner withPublicNetworkAccess(PublicNetworkAccess publicNetworkAccess) {
        if (this.innerProperties() == null) {
            this.innerProperties = new FarmBeatsPropertiesInner();
        }
        this.innerProperties().withPublicNetworkAccess(publicNetworkAccess);
        return this;
    }

    /**
     * Get the privateEndpointConnections property: The private endpoint connection resource.
     * 
     * @return the privateEndpointConnections value.
     */
    public PrivateEndpointConnectionInner privateEndpointConnections() {
        return this.innerProperties() == null ? null : this.innerProperties().privateEndpointConnections();
    }

    /**
     * Validates the instance.
     * 
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (identity() != null) {
            identity().validate();
        }
        if (innerProperties() != null) {
            innerProperties().validate();
        }
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        jsonWriter.writeStringField("location", location());
        jsonWriter.writeMapField("tags", tags(), (writer, element) -> writer.writeString(element));
        jsonWriter.writeJsonField("identity", this.identity);
        jsonWriter.writeJsonField("properties", this.innerProperties);
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of FarmBeatsInner from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of FarmBeatsInner if the JsonReader was pointing to an instance of it, or null if it was
     * pointing to JSON null.
     * @throws IllegalStateException If the deserialized JSON object was missing any required properties.
     * @throws IOException If an error occurs while reading the FarmBeatsInner.
     */
    public static FarmBeatsInner fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            FarmBeatsInner deserializedFarmBeatsInner = new FarmBeatsInner();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                if ("id".equals(fieldName)) {
                    deserializedFarmBeatsInner.id = reader.getString();
                } else if ("name".equals(fieldName)) {
                    deserializedFarmBeatsInner.name = reader.getString();
                } else if ("type".equals(fieldName)) {
                    deserializedFarmBeatsInner.type = reader.getString();
                } else if ("location".equals(fieldName)) {
                    deserializedFarmBeatsInner.withLocation(reader.getString());
                } else if ("tags".equals(fieldName)) {
                    Map<String, String> tags = reader.readMap(reader1 -> reader1.getString());
                    deserializedFarmBeatsInner.withTags(tags);
                } else if ("identity".equals(fieldName)) {
                    deserializedFarmBeatsInner.identity = Identity.fromJson(reader);
                } else if ("properties".equals(fieldName)) {
                    deserializedFarmBeatsInner.innerProperties = FarmBeatsPropertiesInner.fromJson(reader);
                } else if ("systemData".equals(fieldName)) {
                    deserializedFarmBeatsInner.systemData = SystemData.fromJson(reader);
                } else {
                    reader.skipChildren();
                }
            }

            return deserializedFarmBeatsInner;
        });
    }
}
