# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/redhatopenshifthcp/ci.yml
      - sdk/redhatopenshifthcp/azure-resourcemanager-redhatopenshifthcp/
    exclude:
      - sdk/redhatopenshifthcp/pom.xml
      - sdk/redhatopenshifthcp/azure-resourcemanager-redhatopenshifthcp/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/redhatopenshifthcp/ci.yml
      - sdk/redhatopenshifthcp/azure-resourcemanager-redhatopenshifthcp/
    exclude:
      - sdk/redhatopenshifthcp/pom.xml
      - sdk/redhatopenshifthcp/azure-resourcemanager-redhatopenshifthcp/pom.xml

parameters:
  - name: release_azureresourcemanagerredhatopenshifthcp
    displayName: azure-resourcemanager-redhatopenshifthcp
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: redhatopenshifthcp
    Artifacts:
      - name: azure-resourcemanager-redhatopenshifthcp
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagerredhatopenshifthcp
        releaseInBatch: ${{ parameters.release_azureresourcemanagerredhatopenshifthcp }}
