# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/managementservicegroups/ci.yml
      - sdk/managementservicegroups/azure-resourcemanager-managementservicegroups/
    exclude:
      - sdk/managementservicegroups/pom.xml
      - sdk/managementservicegroups/azure-resourcemanager-managementservicegroups/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/managementservicegroups/ci.yml
      - sdk/managementservicegroups/azure-resourcemanager-managementservicegroups/
    exclude:
      - sdk/managementservicegroups/pom.xml
      - sdk/managementservicegroups/azure-resourcemanager-managementservicegroups/pom.xml

parameters:
  - name: release_azureresourcemanagermanagementservicegroups
    displayName: azure-resourcemanager-managementservicegroups
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: managementservicegroups
    Artifacts:
      - name: azure-resourcemanager-managementservicegroups
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagermanagementservicegroups
        releaseInBatch: ${{ parameters.release_azureresourcemanagermanagementservicegroups }}
