# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/nodecustomization/ci.yml
      - sdk/nodecustomization/azure-resourcemanager-nodecustomization/
    exclude:
      - sdk/nodecustomization/pom.xml
      - sdk/nodecustomization/azure-resourcemanager-nodecustomization/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/nodecustomization/ci.yml
      - sdk/nodecustomization/azure-resourcemanager-nodecustomization/
    exclude:
      - sdk/nodecustomization/pom.xml
      - sdk/nodecustomization/azure-resourcemanager-nodecustomization/pom.xml

parameters:
  - name: release_azureresourcemanagernodecustomization
    displayName: azure-resourcemanager-nodecustomization
    type: boolean
    default: false

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: nodecustomization
    Artifacts:
      - name: azure-resourcemanager-nodecustomization
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanagernodecustomization
        releaseInBatch: ${{ parameters.release_azureresourcemanagernodecustomization }}
