// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.resourcemanager.iotoperations.models;

import com.azure.core.annotation.Immutable;
import com.azure.json.JsonReader;
import com.azure.json.JsonSerializable;
import com.azure.json.JsonToken;
import com.azure.json.JsonWriter;
import java.io.IOException;

/**
 * DataflowEndpoint Anonymous Authentication properties.
 */
@Immutable
public final class DataflowEndpointAuthenticationAnonymous
    implements JsonSerializable<DataflowEndpointAuthenticationAnonymous> {
    /**
     * Creates an instance of DataflowEndpointAuthenticationAnonymous class.
     */
    public DataflowEndpointAuthenticationAnonymous() {
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JsonWriter toJson(JsonWriter jsonWriter) throws IOException {
        jsonWriter.writeStartObject();
        return jsonWriter.writeEndObject();
    }

    /**
     * Reads an instance of DataflowEndpointAuthenticationAnonymous from the JsonReader.
     * 
     * @param jsonReader The JsonReader being read.
     * @return An instance of DataflowEndpointAuthenticationAnonymous if the JsonReader was pointing to an instance of
     * it, or null if it was pointing to JSON null.
     * @throws IOException If an error occurs while reading the DataflowEndpointAuthenticationAnonymous.
     */
    public static DataflowEndpointAuthenticationAnonymous fromJson(JsonReader jsonReader) throws IOException {
        return jsonReader.readObject(reader -> {
            DataflowEndpointAuthenticationAnonymous deserializedDataflowEndpointAuthenticationAnonymous
                = new DataflowEndpointAuthenticationAnonymous();
            while (reader.nextToken() != JsonToken.END_OBJECT) {
                String fieldName = reader.getFieldName();
                reader.nextToken();

                reader.skipChildren();
            }

            return deserializedDataflowEndpointAuthenticationAnonymous;
        });
    }
}
