// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.labservices.fluent.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.azure.resourcemanager.labservices.models.EnvironmentDetails;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents the environments details. */
@Immutable
public final class GetEnvironmentResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(GetEnvironmentResponseInner.class);

    /*
     * Details of the environment
     */
    @JsonProperty(value = "environment", access = JsonProperty.Access.WRITE_ONLY)
    private EnvironmentDetails environment;

    /**
     * Get the environment property: Details of the environment.
     *
     * @return the environment value.
     */
    public EnvironmentDetails environment() {
        return this.environment;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (environment() != null) {
            environment().validate();
        }
    }
}
