== Azure Event Hubs Kafka Spring cloud starter client library for Java

This starter for Apache Kafka with Azure Event Hubs helps developers to finish the auto-configuration of Event Hubs with Kafka protocol.

https://mvnrepository.com/artifact/com.azure.spring/azure-spring-cloud-starter-eventhubs-kafka[Package (Maven)] | https://azure.github.io/azure-sdk-for-java/springcloud.html#azure-spring-cloud-autoconfigure[API reference documentation] | https://docs.microsoft.com/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub[Product documentation] | https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/azure-spring-cloud-starter-eventhubs-kafka/eventhubs-kafka[Samples]

=== Getting started

==== Prerequisites

* https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/ENVIRONMENT_CHECKLIST.md#ready-to-run-checklist[Environment checklist].

==== Include the package

1.https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/AZURE_SPRING_BOMS_USAGE.md#add-azure-spring-cloud-dependencies[Add azure-spring-cloud-dependencies].
1. Add dependency. `<version>` can be skipped because we already add `azure-spring-cloud-dependencies`.

[source,xml,indent=0]
----
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-starter-eventhubs-kafka</artifactId>
</dependency>
----

=== Key concepts

Event Hubs provides a Kafka endpoint that can be used by your existing Kafka based applications as an alternative to running your own Kafka cluster. Event Hubs supports Apache Kafka protocol 1.0 and later, and works with your existing Kafka applications, including MirrorMaker.

=== Examples

Please refer to this https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/azure-spring-cloud-starter-eventhubs-kafka/eventhubs-kafka[sample project] illustrating how to use this starter.

=== Troubleshooting

==== Logging setting

Please refer to https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#boot-features-logging[spring logging document] to get more information about logging.

===== Logging setting examples

- Example: Setting logging level of hibernate

[source,properties,indent=0]
----
logging.level.root=WARN
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
----

=== Next steps

The following section provide a sample project illustrating how to use the starter.

===  More sample code
- https://github.com/Azure-Samples/azure-spring-boot-samples/tree/main/eventhubs/azure-spring-cloud-starter-eventhubs-kafka/eventhubs-kafka[Eventhubs Kafka Sample]

=== Contributing
This project welcomes contributions and suggestions.  Most contributions require you to agree to a Contributor License Agreement (CLA) declaring that you have the right to, and actually do, grant us the rights to use your contribution. For details, visit https://cla.microsoft.com.

Please follow https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring/CONTRIBUTING.md[instructions here] to build from source or contribute.
