= Spring Cloud Azure Storage Queue Integration Code Sample shared library for Java

== Key concepts
== Getting started

This code sample demonstrates how to use Spring Integration for Azure Storage Queue.

Running this sample will be charged by Azure.
You can check the usage and bill at https://azure.microsoft.com/en-us/account/[this link].

=== Access key based usage

1. Create https://docs.microsoft.com/en-us/azure/storage/[Azure Storage]

2. Update link:src/main/resources/application.properties[application.properties]

+
....
spring.cloud.azure.storage.account=[storage-account-name]

# Fill storage account access key copied from portal
spring.cloud.azure.storage.access-key=[storage-account-accesskey]

....

=== Credential file based usage

1. Create azure credential file.
Please see https://github.com/Azure/azure-libraries-for-java/blob/master/AUTH.md[how to create credential file].
+
....
$  az login
$  az account set --subscription <name or id>
$  az ad sp create-for-rbac --sdk-auth > my.azureauth
....
+
Make sure `my.azureauth` is encoded with UTF-8.

2. Put credential file under `src/main/resources/`.

3. Create https://docs.microsoft.com/en-us/azure/storage/[Azure Storage].
Or enable auto create resources feature in link:src/main/resources/application.properties[application.properties]:
+
....
spring.cloud.azure.auto-create-resources=true

# Example region is westUS, northchina
spring.cloud.azure.region=[region]
....

5. Update link:src/main/resources/application.properties[application.properties]
+
....

# Enter 'my.azureauth' here if following step 1 and 2
spring.cloud.azure.credential-file-path=[credential-file-path]

spring.cloud.azure.resource-group=[resource-group]

spring.cloud.azure.storage.account=[account-name]
....

=== How to run

2. Update environment if not is Global in link:src/main/resources/application.properties[application.properties]

+
....
# Default environment is GLOBAL. Provide your own if in another environment
# Example environment is China, GLOBAL
# spring.cloud.azure.environment=[environment]
....

3. Update queue name in link:src/main/java/com/example/SendController.java#L30[SendController] and
link:src/main/java/com/example/ReceiveController.java#L22[ReceiveController]

4. Run the `mvn clean spring-boot:run` in the root of the code sample to get the app running.

5. Send a POST request
+
....
$ curl -X POST localhost:8080/messages?message=hello
....

6. Verify in your app's logs that a similar message was posted:
+
....
New message received: 'hello'
Message 'hello' successfully checkpointed
....

7. Delete the resources on http://ms.portal.azure.com/[Azure Portal] to avoid unexpected charges.

== Examples
== Troubleshooting
== Next steps
== Contributing
