// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

package com.azure.security.keyvault.certificates;

/**
 * Fake credential shared in Tests
 */
public class FakeCredentialsForTests {
    /**
     * Fake certificate content
     */
    public static final String FAKE_CERTIFICATE = "MIIKjwIBAzCCCkUGCSqGSIb3DQEHAaCCCjYEggoyMIIKLjCCBJoGCSqGSIb3DQEH"
        + "BqCCBIswggSHAgEAMIIEgAYJKoZIhvcNAQcBMF8GCSqGSIb3DQEFDTBSMDEGCSqG"
        + "SIb3DQEFDDAkBBD6J7VlngzbeYpxVxb5zbUjAgIIADAMBggqhkiG9w0CCQUAMB0G"
        + "CWCGSAFlAwQBKgQQFq79Veolktn9WBVZ2b+yn4CCBBDmBdB0C7F9Lac/Kv5pjH4b"
        + "RFX1HEygcQVBJQpCKq5WuR2ahBZolTfo6mlhWrB0Y/pdNe5QBERrw5PX9hghny19"
        + "S0m9jmwYb2VwTigIGJAqR6Ruik3MJ1Ya57dYNXgpr3smhgYNe66Jk8sHbFiwlSU7"
        + "Hsq69+1EZwwKBHerGfpMux4vWAWAIHorJgZxrXAuce+mSxDxkASe+Ud/bqq0no3q"
        + "qsad60l2SgTElwpBCrMkac8bUHwOg6jOJltPRSfWjfSiqVt/14OIS5HQwUaA6ZyP"
        + "sD3poTAaDu35d3Xou7f7oZlN5AeCNnoD/uQlA5d/nXEyCC/UXbXj9O+vDXKfaS7Y"
        + "naUqKSOcqxCj9NRsLAJWuE06oOFxrZJu+UbcANZAUqLW6GD8D7kTgoZmakE6QxT0"
        + "Q1tOtEV2/pxhAHKj3V8IiWQ2NdodigO52UcGIt8Q4awbydy6RPFMppsi8WBTXDtP"
        + "bui8V4AJvtrm5jRGdW7mzJvkqeUVR/IeQ/7L5hpcr1hg1EVs43ax29VF6VmMiVKa"
        + "Y3Itiqs49fet6Qburgf11AyrP9RuipJD5hQd1YmlIvpySLkxc2/PMGEsdgC4BTIz"
        + "I0MszHaQPvsgKxGTdf6keV4yZSWUyEOAyFCmuynfOCwSya6Cbm74YAXXj4IdA1dY"
        + "6kOgNgfTM8Tr3KmaBSNbenwAXXPVHIJacqIMRTUIQ/+be0dwsgJ5FJi0/5poYrDj"
        + "XLyXT25OOTFZVAzGwVcm5hlFNQUULV7bAaJOH2ZtK3uoTHuH83FCfRSRqeOqEhZJ"
        + "Z0DF2yEG2yuEHOT2OqcIYuRnl1HbGdYFgbwoa9UTMOYG8HkEgzKFTXoqmKOC38zu"
        + "W+1pKLn+uiTkeyCOjAq99Mwve2fFDdQHXcSmv24ZFsiHSctzDQe9xJUBtRtm38+d"
        + "GkniMuusmxBIhgMqPeG1g7tqS7OrX+r9wZieBqL3aaabXAXQbuQZ3tFyZDzWfA5w"
        + "lWY0mc7rmqau70XTV90eGxUtT4IYeLuTbjVsPBYahsupEbujrkeo4kS8cp6AyIhl"
        + "WLzcXYzwAnIcbQJkw6nb/JyCrz9/mASpQmKpX4syj+4wcFATwDDt4KjblAendcJw"
        + "bguM4isaPCxP48hg4Tj0CLLSRNtMfXIjKltJWkhjXzQLEzcCTeWLAUzzm9mNyDOZ"
        + "EVso2Y1jN6Xqdm6D1bRuHp0TsKlHdkyBwBCkFPph+fCgKrASmbgSzX8bilqzOU/r"
        + "8Ql+ot6br42IPIm6Cwn6sCwdiS0chx0mr52n3Fef7Aurluu6x/xnNT+wLoURXHNe"
        + "FqN0nKZBgKWRQIUKAkpK+02tN0TFtUWbHjJ0EAsNwAaSoTwqXNgEmb8JPR1BRCod"
        + "kYfAnHlnvBy83IMiXMz0lDCCBYwGCSqGSIb3DQEHAaCCBX0EggV5MIIFdTCCBXEG"
        + "CyqGSIb3DQEMCgECoIIFOTCCBTUwXwYJKoZIhvcNAQUNMFIwMQYJKoZIhvcNAQUM"
        + "MCQEEEaqp++BjdYKmeKmJMqBDE0CAggAMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUD"
        + "BAEqBBB8PJ1Qo62GUuy2gDROrqH8BIIE0Byd3Rzee8m9fS7xEV6Z5QM86PEOyziF"
        + "nzWe8WRrbTN62u9JPAfYvXeeCRdr8QKkvw8mJXUUNHYmwo56ExR/JSJu/vQIl7FN"
        + "jtGzwQHQtUTNcZuAsiFrZvYq4vAI0wnwmtW/ApQCylbERyZp8DRx3fT90QTAGz9s"
        + "T9RreOeN8qUj0UY6/8eD3vZJ2sG+QpHK5cv1H++ZhbfgZgR8aaupu6xXKQdTHg7P"
        + "ors42O7Q40Sk/LvWVHfA2tYPr5QfeB1tyjhSnwx1wExlWb01XvRq1IkP8K4SD4Ss"
        + "7Smo7SmWprzjIFcpTWXI0MS2sFIzJICxih3eUoWvRYWZk0J8H1qVq4yDke0q9ah7"
        + "FdCOt2Ah7JPscb+ahGjQjNNWsfC3INSNLABxB3b3RlJLCY9D/hG5a2auDaF/0tXX"
        + "UhrRfUZhW70Cc345I4hdrX9xze4kSdF5h9Uzzv2OzzFcojM/7CYG3ya2pyMn1CQH"
        + "B/SY2XqweINrqVRWiBEhD1r/SJ1Sq2uvMp6WmctKKOh6JNErFabxd/GybrcYlhZO"
        + "a6SnH23xpMonPzAzW43p8C41GDIizUMFvbxvkPFWBbsSJuUUoGvR6sHvKGOLs72Z"
        + "D0ruInfTeZxD15NX8zd+pZDEyFWVH0sxZjOXouJr3RM28UvLu9uuIoz7+1/p3rns"
        + "NX7tBV7zDspe5Tsb3t49vtO5wxdGAIAEK+5MrbvuP1w2T6aQYwF5DSzckDeZREGn"
        + "GjEyTnzFRn/1FTKgfPkBUa8AIl1CbYYNebusVZSoB19+gDCH3oyzF4+Qr5mKpkEF"
        + "LFbV4Sxvbk8vxNthubcuMXP+QGJA5o6jNfpvM8mGcZR8tO8J7Kq+pKv8AdtkRHuj"
        + "HVuenB5sdgKR5hJB7cOqQBush+6i+yA4dFWbt1vblABGCueJYw7/czhQx4iO6JEx"
        + "P2TZaFq7+SuvIdEOB7uMwnPIQFv1ukBcx8eiWspK0qsKeIpqDVwaypJLgqKEOL9U"
        + "0YRXxeH1XjxBWGipvRhmo4C8NYt9Lwt1FUh9nEwjmXSapaA0zUO2pLpzy3rdIGW9"
        + "gdRfKvNie0w8jwuvgzMY9t3u04MHyKQ2h1NIOXrOfZk/dOrgpUpRqG1bPhS/El1s"
        + "cwZglmVX6PU4fItXFkQpR+WxQpVncOlS/e4ac3RYXAq/ch84vQ+vXRaWruNB9nSy"
        + "y1d/bwJWtF1I0ZWE+nExyWdlUBp89dIrYSFw/cfwark615ROE1akA7wU68Y5K7HO"
        + "99t4V9NwleGhfQ2mf94QjkfVyszYsrCBqSWhrGYTQ6JoTKquR0Xz6vZnMmUvaUK1"
        + "Ddv96lmfWBSIJ/urWMSRL75jIH5bYNnx5gAyorXqEKJAtt1yGftZYUXaOOfHvXJc"
        + "FOlXIGAF9EtmaPnefC9HSTmnrNSJEB9u+hiaXBzVkI2oJG/GM6aLOTdYyMDC8fXw"
        + "30h0j+cp4IhoYythftmQZ1rz9oVZOZgIQJjViYwPHY2gOE/BZ+bBKjtdZ4cDYOHS"
        + "9g3DrtexeLpjmWSqITa+x/KV8KWmE0FMcsDauKNVILFs607F9hqd+4azfqhtpT8Q"
        + "0u84RgoVrmFIajhaNl5+06KVGCRAkmwQkxYHiY8SkuPTo4dh0/9AycqMODL5Zjh6"
        + "a6MHpGSGG+WXMSUwIwYJKoZIhvcNAQkVMRYEFHO0MZzfOOB5cIRTXZwC/QTUsrLm"
        + "MEEwMTANBglghkgBZQMEAgEFAAQguefMRfuN/2S1v8baZNWXyR/9lVxdKylJSNnO" + "ULN2mZ4ECN9bsOpidibOAgIIAA==";

    public static final String FAKE_PEM_CERTIFICATE
        = "-----BEGIN PRIVATE KEY-----\n" + "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5VhSKgC+hsi3Y\n"
            + "yawJItMJS1//3x3Rs3EY1ZjCFxFvTGNJZQbBFPlBWE7oiyG7pTe+QaHfevBXJ/Dd\n"
            + "aHfZy96BgrgYwbBBf3aq50ZoGjxuAJVdVW72rEL+sjKKP+S7WWNDGT3cNrf8SZq0\n"
            + "oguLHrNBGUkJfTwwCGGyJE5ULZFUaurt/3DTmLX/FVFlJZAV1BYhpWzCgDE4DtR0\n"
            + "aD4loGtWnOiAEnRUg32YBbfXx0g2zvQSKBU2B+S33GRNJ+jaceyo6MigUbJqsntO\n"
            + "BMd/Og3j0AUnzVldFbRs3xDWC1lEJ8xBVCuIeE7HZsTdi8Qyjg0x5hkCOSmwErzY\n"
            + "rPMSmz/zAgMBAAECggEALVRVb86MV9L5jaU9s3pV/Vb3IuDSLUDjL3zGgOoddIhN\n"
            + "XF0eOslDcW0E17F3zapKKPlqevtZnyeArNZpQdawFCMBneR5lHt1bbVlLf8Euq7f\n"
            + "2VUU77YQKLUy0UdxTTU+puGclKi5dTYXZYigpCUdGJXznCOKPgE+y9A/bC0891VI\n"
            + "FCqCSoDwdMZa62HLQ0m7MT62ooK8EJZt96NYmhMmX6+4Si2N2YL42A2AI8Y0eC+/\n"
            + "6ZKiqn98wGcOh0RyShW6AS2JOsKAr+p1S57v45kU7gKRQIBwmI1a5EFid/q0jrI8\n"
            + "JQPxgOHR+E/Fpp1idYXq7h2cJ0TlY8JO2vU50KOUQQKBgQDwFbi+DZ5mlvmAN/vf\n"
            + "Ck5PsYwf2+uF3YzGEQVs+CbK3h1DxIS+taSUZfVFsHR8X9npwOFZAQOJbPCUG+3K\n"
            + "W85e2HeugOTCMuONpdSwS2/CX/c13sr1vVK7j84rZwVyVcnk5hLgT2s70nhPnn+B\n"
            + "s5bIgQuVfyDY1EINtDqbHImzEwKBgQDFn0QepEJbMqgUazLxylQtZ1UMzie0pL/j\n"
            + "IzWVT7iT2y6nl9QsXUO26xVYkEeYvfWAe25fHBVxEB5pIDv2fqN9GBRNwKAqleQ2\n"
            + "4gwZhollaynoEjey77q9bO3HwO+Q435sYBfG24kPSARa2x3PjcPZqxRTGxMhdkrB\n"
            + "zuudjJr7oQKBgQDJdlDKGn97MuE2+MOATBOeyCv/Z/nhISJJ6mqVID7dKTmBbly9\n"
            + "84qhhFUnH4UAASbJAjOXDkS7gxD2F+GYVyV7bUYwxrQvSaitaiRps0Oa5hB5wfSp\n"
            + "9S6BeZDV1uM5KEf8rhvU4o/naRvQI/53Bg5XPgJMdptHmAW9nik3k+DwxQKBgBU0\n"
            + "WaLQDS6r6M0IE5dOFmooxD9zf18qrkw44u76dtumkQL6j5GTEEj4QHoYQRZqi4UV\n"
            + "uWoLIWHYUOsGwmhYfkJV6xfMq2LmYm5hIts6TFPNg9ma2s8gWfEpVvowAYSSZGZM\n"
            + "iUCVHce9+nmlOTWkCHe6m5uvNAZLIwpYoX9uLtMBAoGAHpv1byXQIhXixggRWQhS\n"
            + "swWidB/BM59Ca/91UKiHclYOElGhkiJfQ9IzuAJPRTLAb7FtaSaFk1BYrkqhUAD+\n"
            + "bxBYfZXXmL6ZLLfG62CMUxM+kmSkJEsC5pUQLsROR4CYHr1k/mJ38BBfIZtAGkNf\n" + "ITuwWNGYas8uoi/1xCrRRx8=\n"
            + "-----END PRIVATE KEY-----\n" + "-----BEGIN CERTIFICATE-----\n"
            + "MIID3TCCAsWgAwIBAgIUDqp5V2ClLE4cUzry8oN6EQrnVY4wDQYJKoZIhvcNAQEL\n"
            + "BQAwgZYxCzAJBgNVBAYTAlVTMQswCQYDVQQIDAJXQTEQMA4GA1UEBwwHUmVkbW9u\n"
            + "ZDESMBAGA1UECgwJTWljcm9zb2Z0MRswGQYDVQQLDBJBenVyZSBTREsgZm9yIEph\n"
            + "dmExEDAOBgNVBAMMB3Zjb2xpbjcxJTAjBgkqhkiG9w0BCQEWFnZpY29saW5hQG1p\n"
            + "Y3Jvc29mdC5jb20wHhcNMjUwMzAyMDkzNzQxWhcNMjYwMzAyMDkzNzQxWjCBljEL\n"
            + "MAkGA1UEBhMCVVMxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdSZWRtb25kMRIwEAYD\n"
            + "VQQKDAlNaWNyb3NvZnQxGzAZBgNVBAsMEkF6dXJlIFNESyBmb3IgSmF2YTEQMA4G\n"
            + "A1UEAwwHdmNvbGluNzElMCMGCSqGSIb3DQEJARYWdmljb2xpbmFAbWljcm9zb2Z0\n"
            + "LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALlWFIqAL6GyLdjJ\n"
            + "rAki0wlLX//fHdGzcRjVmMIXEW9MY0llBsEU+UFYTuiLIbulN75Bod968Fcn8N1o\n"
            + "d9nL3oGCuBjBsEF/dqrnRmgaPG4AlV1VbvasQv6yMoo/5LtZY0MZPdw2t/xJmrSi\n"
            + "C4ses0EZSQl9PDAIYbIkTlQtkVRq6u3/cNOYtf8VUWUlkBXUFiGlbMKAMTgO1HRo\n"
            + "PiWga1ac6IASdFSDfZgFt9fHSDbO9BIoFTYH5LfcZE0n6Npx7KjoyKBRsmqye04E\n"
            + "x386DePQBSfNWV0VtGzfENYLWUQnzEFUK4h4TsdmxN2LxDKODTHmGQI5KbASvNis\n"
            + "8xKbP/MCAwEAAaMhMB8wHQYDVR0OBBYEFMbPqDuIJ7fPGg48cOpimuptwmQTMA0G\n"
            + "CSqGSIb3DQEBCwUAA4IBAQCKMhMhjLygy8yDNkvfquWpbp6Gce206bveRqV0/sGF\n"
            + "lz1T0ut8+CmKRLBft7DhHYZdmz+43MaNz7ClvSLgvQnYHeZwswHwVRx4j99M7L4r\n"
            + "l366HJYggcsITjtGjxY1kPbQL1MLq7dxL0uCsEIT6JqxL+tP01DdZ5CikO5+JIZa\n"
            + "qFYVElKbdtQJTNxpM5Zb8YjMl0z9ZVGmIoGee6Rueu6sDgBDJ5KbZ5R856OcnZSp\n"
            + "QW25YQXWpO0Z8ggt7EDOnzzBieJb4svNwwq5F+rkiAIzDCp9z1jjBYWoPLfelDLX\n"
            + "GCTBsJJ1GDj/2hrSqQnW7Z7SxPt6BQVK1BlN6l6blOn1\n" + "-----END CERTIFICATE-----\n";

    public static final String FAKE_PEM_CERTIFICATE_FOR_MERGE
        = "-----BEGIN CERTIFICATE-----\n" + "MIIDazCCAlOgAwIBAgIUYju9zymmCCF7rCaROzfZs0pNgmkwDQYJKoZIhvcNAQEL\n"
            + "BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM\n"
            + "GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0xOTA4MjgyMjU0MTNaFw0xOTA5\n"
            + "MjcyMjU0MTNaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw\n"
            + "HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB\n"
            + "AQUAA4IBDwAwggEKAoIBAQD0YrMz5atoPmTTxLtCO69kM3E97bdjJgyAVZJS9mP3\n"
            + "HQyHkFNb09eDeAAzcZLR5nYXX7yweowTWVcIe3k9+Z/tUeVrAlOVe2COaIHAUZIh\n"
            + "jELq/u8257/8MqqbKXhsyrWNAVDyKndDgvbbgxNsUTbMoAe9BCL/5fzowsnPLaCI\n"
            + "MCYRaQJUySbIoTmKi11hF09CFFSkL9nvfQODFyEde6JHPWrVRse2lioPLJeC9LoU\n"
            + "GNNZnbqry+UbHp4vORPp6OQTqBTm1ZVWPzCuYuWUmEe27K7zghEJr/Yx0OLq9kI5\n"
            + "H960CSOkdhsOTcBkORfhivSQnmOn2RnCPIEsUTzjwXNZAgMBAAGjUzBRMB0GA1Ud\n"
            + "DgQWBBQIAunu6y1BmFSDfFNfTnqFggB0gzAfBgNVHSMEGDAWgBQIAunu6y1BmFSD\n"
            + "fFNfTnqFggB0gzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAr\n"
            + "+RM7gbqWRXnWJwE/hV/ZI2hXAhDN4RYQ4fWMJfg/E9wcLeqqRtJhXbqpJW08IZWp\n"
            + "QKcWfrFcfZ3ZxVAi5Ey+iuvD2VeBf9v5RZI4c9JqswS9xG2A1x/BeGcUk1y/q9E5\n"
            + "4whf5fLSJQVxK+C53yemoHPrBg8zVhLJv5SG7Uw7jcqiQvu2aHGGWPLiO7mmMPtP\n"
            + "qO/I+6FjXuBpNomTqM897MY3Qzg43rpoCilpOpkRtMHknfhFxt05p+Fn73Fb60ru\n"
            + "ZsFRA52lsEBxGmI0QmXGjwkUZFwQTXEDUWwId3VJxoHRZwv1gmHfwhkYt+mNWJDa\n" + "mU7AMDzlQRwGC8hpWJRT\n"
            + "-----END CERTIFICATE-----\n" + "-----BEGIN RSA PRIVATE KEY-----\n"
            + "MIIEpQIBAAKCAQEA9GKzM+WraD5k08S7QjuvZDNxPe23YyYMgFWSUvZj9x0Mh5BT\n"
            + "W9PXg3gAM3GS0eZ2F1+8sHqME1lXCHt5Pfmf7VHlawJTlXtgjmiBwFGSIYxC6v7v\n"
            + "Nue//DKqmyl4bMq1jQFQ8ip3Q4L224MTbFE2zKAHvQQi/+X86MLJzy2giDAmEWkC\n"
            + "VMkmyKE5iotdYRdPQhRUpC/Z730DgxchHXuiRz1q1UbHtpYqDyyXgvS6FBjTWZ26\n"
            + "q8vlGx6eLzkT6ejkE6gU5tWVVj8wrmLllJhHtuyu84IRCa/2MdDi6vZCOR/etAkj\n"
            + "pHYbDk3AZDkX4Yr0kJ5jp9kZwjyBLFE848FzWQIDAQABAoIBAHrhegv5SrOy083r\n"
            + "mODX0/wFJcam1dRD2HtbC6UtgNxLPfaYKmH85duUJj23uMRUJkLgf6cZJ3+/J1T7\n"
            + "iN4Ru0mAKWQiGlcKX2WbxMon+dtmhGtW3n90DgPIkiJMuuGxF5Kb+9CYa7mFi4ya\n"
            + "ntSTDYPcX6e6AcM8KGv9La4/2f0/hQKCN3jZbnQ/GqjnJdxrAV1KV0IMoNPpZmat\n"
            + "Sa0EZ9eiR57/xAe1OxceEt0nO7hAl+jX7tFEGvaNClKG2OMgZ+oHOxI+s9jW8DyD\n"
            + "wRJbd0hxUl/KXLxzyeFTBdLxB+SQtlcr4w5khyt3AvlKd4Iveqkq2FBCtfATYitt\n"
            + "+Ic61IUCgYEA/j4mMdo+qokzACmGJWEquC6yNoUI5aYsHTRVvX0sLpBX7MapIEwM\n"
            + "zHdvMEFBxw8rs7ll1xELW+dnbIZqj/ou43E3+PSgovdFGOA8kQlPpcIIutTEZQh7\n"
            + "dlWzvAVZr0iO4xfXY2gFQot41fY4yRy8Q14ayo/VjQK4uKlnGqqlmwsCgYEA9hMc\n"
            + "FIAYpit7779tKD+O4vEkMoTkIxqSAZUuOZ5qB5UaF4Y/+MIGZUnrjJlGLnoFQmsP\n"
            + "CVPVMOQKV7yjg0LBadeDHEjESwHJNk0qxPSXWuXGlu01yVkqUehNumSBdnSLBmjR\n"
            + "jNIxPVEmW9d6+eAzIFiTkwqM9cAuLb75DL++iasCgYEAxhqzNEE0dzl0zfmNF29B\n"
            + "FEb+glDi/96dnRv8eywf0yCSAmNBwXLAvkmKD/WpRWxixyX9XrlfOntzMTMDsbBl\n"
            + "/L9pt8kVqiY2Zw3C49h3gVdR6hKD/Z3AZhKdfDJHEbfd7sHTCRgykQmQXFgBI2QK\n"
            + "pguboJ627atjODB3sGWrqMUCgYEA2QoJ3lsNYqM/8TpaQQGuOaSPVK+5uOyakyLN\n"
            + "XqzGwGFWXiFfEz2u/m+wfpZCPIQLV4WuAYAbrb+1D6WmYwPiLESVs8DKwY2Vt3tg\n"
            + "mc9SIC5CdqRKqIkoto264Qf82En6xXB2Q0qxe2+z8ZWhNfv1nDYEE9FeevNCx76F\n"
            + "VCVbHXkCgYEA4+FD1q6iwl9wsAOKFVo+W044/MhKHDsyIED3YOzeRTAWRl2w/KX0\n"
            + "c5ty2KecGu0cVXoAv2YUttHsuMZfm/QdosZr9UB4CR2lmzRys3LSx6QzCkZeMb/s\n"
            + "QOMs6SYCPXggdXCAu9EVf5+TtYQg7aQNTTuYErlyq2g/tk3un8bHTwI=\n" + "-----END RSA PRIVATE KEY-----";
}
