// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.ai.agents.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import java.util.Collection;

/**
 * Defines values for ImageGenToolBackground.
 */
public final class ImageGenToolBackground extends ExpandableStringEnum<ImageGenToolBackground> {
    /**
     * Static value transparent for ImageGenToolBackground.
     */
    @Generated
    public static final ImageGenToolBackground TRANSPARENT = fromString("transparent");

    /**
     * Static value opaque for ImageGenToolBackground.
     */
    @Generated
    public static final ImageGenToolBackground OPAQUE = fromString("opaque");

    /**
     * Static value auto for ImageGenToolBackground.
     */
    @Generated
    public static final ImageGenToolBackground AUTO = fromString("auto");

    /**
     * Creates a new instance of ImageGenToolBackground value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public ImageGenToolBackground() {
    }

    /**
     * Creates or finds a ImageGenToolBackground from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding ImageGenToolBackground.
     */
    @Generated
    public static ImageGenToolBackground fromString(String name) {
        return fromString(name, ImageGenToolBackground.class);
    }

    /**
     * Gets known ImageGenToolBackground values.
     * 
     * @return known ImageGenToolBackground values.
     */
    @Generated
    public static Collection<ImageGenToolBackground> values() {
        return values(ImageGenToolBackground.class);
    }
}
