name: Spring Docker Tests

on:
  pull_request:
    paths:
      - '.github/workflows/spring-docker-tests.yml'
      - 'sdk/spring/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  spring-docker-tests:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up JDK 17
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6.0.1
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Verify Docker
        run: |
          docker version
          docker info

      - name: Build spring docker test dependencies
        run: >
          mvn -f sdk/spring/pom.xml
          -pl spring-cloud-azure-testcontainers,spring-cloud-azure-docker-compose
          -am
          install
          -Dcheckstyle.skip=true
          -Dcodesnippet.skip=true
          -Denforcer.skip=true
          -Djacoco.skip=true
          -Dmaven.javadoc.skip=true
          -Drevapi.skip=true
          -DskipTests
          -Dspotbugs.skip=true
          -Pdev
          -T 4
          -ntp
          -DfailIfNoTests=false

      - name: Run spring docker-tagged tests
        run: >
          mvn -f sdk/spring/pom.xml
          -pl spring-cloud-azure-testcontainers,spring-cloud-azure-docker-compose
          test
          -Pdocker-tests
          -Dcheckstyle.skip=true
          -Dcodesnippet.skip=true
          -Denforcer.skip=true
          -Djacoco.skip=true
          -Dmaven.javadoc.skip=true
          -Dspotbugs.skip=true
          -T 4
          -ntp
